import { describe, it, expect } from "vitest";
import { chacha20poly1305 } from "@noble/ciphers/chacha";
import {
  deviceId,
  authSignature,
  deviceIdentityFromSecret,
  ecdhSharedSecret,
  getPublicKey,
  deriveSessionKey,
  encrypt,
  decrypt,
} from "../crypto";
import { hexToBytes, bytesToHex } from "../util/base64url";
import { PROTO_VERSION, type Envelope } from "../types/relay-protocol";

// Known-answer vectors generated by the Rust `relay-client` crate (X25519
// ECDH + HKDF-SHA256 + ChaCha20-Poly1305 AEAD + device identity). The phone's
// TS crypto MUST reproduce these byte-for-byte or pairing/E2E silently fails.
// Constants pinned to crates/relay-client/src/{crypto,identity,pairing}.rs.

const DEVICE_SECRET_HEX =
  "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
const EPHEMERAL_SECRET_HEX =
  "6465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80818283";
const PC_PUBLIC_HEX =
  "4d5bab89b0733d9d8dcecf04f321c90b761b7765a6bdb2bddbfad3e7abdf1f66";
const PHONE_EPH_PUB_HEX =
  "7d9c24316539825c1896e57f28197746793ce60cbee3ad47da9d07b85fa55e2a";
const SHARED_HEX =
  "39d06aeaf46f39d97533b0e3e890eace641f8161740697744d18be7c3f438c73";
const SESSION_KEY_HEX =
  "5252f3e4ec22d70caef4b8039280015c28e7044838ee3784a351aa1d0fa5b2a2";
const DEVICE_ID = "7t2IPaCpRRWT3Ao45YP7dw-ifbvtIJwgQE4HXmjE8Mk";
const AUTH_SIGNATURE = "ET22fKZMPjCbm-rZSMyhfORfaBZhRxPentPXnNXw_mU";
const AUTH_TS = 1700000000000;
const AEAD_NONCE_HEX = "aaaaaaaaaaaaaaaaaaaaaaaa";
const AEAD_AAD = "pc-device-id";
const AEAD_PLAINTEXT = "kodex-e2e-kat";
const AEAD_CIPHERTEXT_HEX =
  "2f8aea6e3e0a5786305a38a6c7ed790e5112e215baca404700741cfd7a";

describe("device identity conformance", () => {
  const identity = deviceIdentityFromSecret(hexToBytes(DEVICE_SECRET_HEX));

  it("device_id_is_stable_for_same_secret", () => {
    expect(deviceId(identity)).toBe(DEVICE_ID);
  });

  it("auth_signature_is_deterministic_for_same_timestamp", () => {
    expect(authSignature(identity, AUTH_TS)).toBe(AUTH_SIGNATURE);
  });
});

describe("ECDH conformance", () => {
  it("public key derivation matches the Rust crate", () => {
    const pubBytes = getPublicKey(hexToBytes(EPHEMERAL_SECRET_HEX));
    expect(bytesToHex(pubBytes)).toBe(PHONE_EPH_PUB_HEX);
  });

  it("ecdh_yields_symmetric_shared_secret", () => {
    // Phone computes X25519(ephemeral_secret, pc_static_public) and must equal
    // the Rust-computed shared secret (PC side: X25519(pc_secret, phone_pub)).
    const shared = ecdhSharedSecret(
      hexToBytes(EPHEMERAL_SECRET_HEX),
      hexToBytes(PC_PUBLIC_HEX),
    );
    expect(bytesToHex(shared)).toBe(SHARED_HEX);
  });
});

describe("session key conformance", () => {
  it("HKDF derivation matches SessionKey::derive", () => {
    const key = deriveSessionKey(hexToBytes(SHARED_HEX));
    expect(bytesToHex(key.bytes)).toBe(SESSION_KEY_HEX);
  });
});

describe("AEAD primitive conformance (fixed nonce KAT)", () => {
  const key = deriveSessionKey(hexToBytes(SHARED_HEX));
  const nonce = hexToBytes(AEAD_NONCE_HEX);
  const aad = new TextEncoder().encode(AEAD_AAD);
  const plaintext = new TextEncoder().encode(AEAD_PLAINTEXT);

  it("encrypt matches the Rust crate ciphertext", () => {
    const cipher = chacha20poly1305(key.bytes, nonce, aad);
    const ct = cipher.encrypt(plaintext);
    expect(bytesToHex(ct)).toBe(AEAD_CIPHERTEXT_HEX);
  });

  it("decrypt recovers the plaintext", () => {
    const cipher = chacha20poly1305(key.bytes, nonce, aad);
    const pt = cipher.decrypt(hexToBytes(AEAD_CIPHERTEXT_HEX));
    expect(new TextDecoder().decode(pt)).toBe(AEAD_PLAINTEXT);
  });
});

describe("AEAD envelope round-trips and rejects tampering", () => {
  const key = deriveSessionKey(hexToBytes(SHARED_HEX));
  const toDeviceId = "dev-phone";
  const envelope: Envelope = {
    proto_version: PROTO_VERSION,
    id: "00000000-0000-4000-8000-000000000000",
    type: "control_request",
    payload: { op: "cancel", request_id: "00000000-0000-4000-8000-000000000000" },
  };

  it("encrypt_decrypt_roundtrip_recovers_envelope", () => {
    const enc = encrypt(key, toDeviceId, envelope);
    expect(enc.to_device_id).toBe(toDeviceId);
    expect(enc.nonce).toHaveLength(12);
    expect(enc.ciphertext.length).toBeGreaterThan(0);
    expect(decrypt(key, enc)).toEqual(envelope);
  });

  it("wrong_key_fails_to_decrypt", () => {
    const otherKey = deriveSessionKey(new Uint8Array(32).fill(0x7));
    const enc = encrypt(key, toDeviceId, envelope);
    expect(() => decrypt(otherKey, enc)).toThrow();
  });

  it("to_device_id_mismatch_fails_aad_check", () => {
    const enc = encrypt(key, toDeviceId, envelope);
    const tampered = { ...enc, to_device_id: "dev-other" };
    expect(() => decrypt(key, tampered)).toThrow();
  });

  it("tampered_ciphertext_fails", () => {
    const enc = encrypt(key, toDeviceId, envelope);
    const bytes = Uint8Array.from(enc.ciphertext);
    bytes[0] ^= 0xff;
    const tampered = { ...enc, ciphertext: Array.from(bytes) };
    expect(() => decrypt(key, tampered)).toThrow();
  });
});
